camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
  database:
    type: h2
  generic-properties:
    properties:
      telemetry-reporter-activate: false
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
